MusicLibraryBrowser/Models/Artist.cs
using System;
using System.Collections.Generic;

namespace MusicLibraryBrowser
{
    public partial class Artist
    {
        public Artist()
        {
            Work = new HashSet<Work>();
        }

        public int ArtistId { get; set; }
        public int GenreId { get; set; }
        public string ArtistName { get; set; }
        public int? ImageId { get; set; }

        public Genre Genre { get; set; }
        public ICollection<Work> Work { get; set; }
    }
}

MusicLibraryBrowser/ViewModels/ArtistViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicLibraryBrowser.ViewModels
{
    public class ArtistViewModel
    {
        public int ArtistId { get; set; }
        public int GenreId { get; set; }
        public string GenreName { get; set; }
        public string ArtistName { get; set; }
        public int? ImageId { get; set; }
        public byte[] ImageData{ get; set; }
    }
}

MusicLibraryBrowser/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;
using MusicLibraryBrowser.ViewModels;

namespace MusicLibraryBrowser.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly musiclibraryContext _context;

        public ArtistsController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Artists
        public async Task<IActionResult> Index(int? genreid)
        {
            var musiclibraryContext = _context.Artist.Include(a => a.Genre);

 //         var artists = from a in musiclibraryContext select a;
            var artists = (from a in _context.Artist
                          join i in _context.Image
                          on a.ImageId equals i.ImageId
                          into a1
                          from b1 in a1.DefaultIfEmpty(new Image())
                          select new ArtistViewModel
                          {
                              ArtistId = a.ArtistId,
                              GenreId = a.GenreId,
                              GenreName = a.Genre.GenreName,
                              ArtistName = a.ArtistName,
                              ImageId = a.ImageId,
                              ImageData = b1.Data
                          });

            if (genreid != null)
            {
                artists = artists.Where(a => a.GenreId == genreid);
                var genrename = from g in _context.Genre where g.GenreId == genreid select g.GenreName;
                ViewData["GenreName"] = genrename.FirstOrDefault().ToString();
            }
            return View(await artists.OrderBy(a => a.ArtistName).ToListAsync());
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            var image = await _context.Image.FindAsync(id);

            byte[] photoBack = image.Data;

            return File(photoBack, "image/png");
        }

        // GET: Artists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist
                .Include(a => a.Genre)
                .FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName");
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArtistId,GenreId,ArtistName")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName", artist.GenreId);
            return View(artist);
        }

        // GET: Artists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName", artist.GenreId);
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtistId,GenreId,ArtistName")] Artist artist)
        {
            if (id != artist.ArtistId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artist.ArtistId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName", artist.GenreId);
            return View(artist);
        }

        // GET: Artists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist
                .Include(a => a.Genre)
                .FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artist.FindAsync(id);
            _context.Artist.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artist.Any(e => e.ArtistId == id);
        }
    }
}

MusicLibraryBrowser/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;

namespace MusicLibraryBrowser.Controllers
{
    public class ImagesController : Controller
    {
        private readonly musiclibraryContext _context;

        public ImagesController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Images
        public async Task<IActionResult> Index(int? id)
        {
            var images = from i in _context.Image select i;
            if (id != null)
            {
                images = images.Where(i => i.ImageId == id);
            }
            return View(await images.ToListAsync());
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            var image = await _context.Image.FindAsync(id);

            byte[] photoBack = image.Data;

            return File(photoBack, "image/png");
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Images/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ImageId,Data")] Image image)
        {
            if (ModelState.IsValid)
            {
                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(image);
        }

        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ImageId,Data")] Image image)
        {
            if (id != image.ImageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.ImageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(image);
        }

        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.ImageId == id);
        }
    }
}

MusicLibraryBrowser/Controllers/WorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;

namespace MusicLibraryBrowser.Controllers
{
    public class WorksController : Controller
    {
        private readonly musiclibraryContext _context;

        public WorksController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Works
        public async Task<IActionResult> Index(int? id)
        {
            var musiclibraryContext = _context.Work.Include(w => w.Artist).ThenInclude(g => g.Genre);
            var works = from w in musiclibraryContext select w;
            if (id != null)
            {
                works = works.Where(w => w.ArtistId == id);
            }
            return View(await works.ToListAsync());
        }

        // GET: Works/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work
                .Include(w => w.Artist)
                .FirstOrDefaultAsync(m => m.WorkId == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        // GET: Works/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName");
            return View();
        }

        // POST: Works/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkId,ArtistId,WorkName")] Work work)
        {
            if (ModelState.IsValid)
            {
                _context.Add(work);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName", work.ArtistId);
            return View(work);
        }

        // GET: Works/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work.FindAsync(id);
            if (work == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName", work.ArtistId);
            return View(work);
        }

        // POST: Works/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkId,ArtistId,WorkName")] Work work)
        {
            if (id != work.WorkId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(work);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkExists(work.WorkId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName", work.ArtistId);
            return View(work);
        }

        // GET: Works/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work
                .Include(w => w.Artist)
                .FirstOrDefaultAsync(m => m.WorkId == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        // POST: Works/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var work = await _context.Work.FindAsync(id);
            _context.Work.Remove(work);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkExists(int id)
        {
            return _context.Work.Any(e => e.WorkId == id);
        }
    }
}

MusicLibraryBrowser/Views/Artists/Create.cshtml
@model MusicLibraryBrowser.Artist

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class ="form-control" asp-items="ViewBag.GenreId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ArtistName" class="control-label"></label>
                <input asp-for="ArtistName" class="form-control" />
                <span asp-validation-for="ArtistName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicLibraryBrowser/Views/Artists/Delete.cshtml
@model MusicLibraryBrowser.Artist

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ArtistName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArtistName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ArtistId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MusicLibraryBrowser/Views/Artists/Details.cshtml
@model MusicLibraryBrowser.Artist

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ArtistName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArtistName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ArtistId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MusicLibraryBrowser/Views/Artists/Edit.cshtml
@model MusicLibraryBrowser.Artist

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ArtistId" />
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistName" class="control-label"></label>
                <input asp-for="ArtistName" class="form-control" />
                <span asp-validation-for="ArtistName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicLibraryBrowser/Views/Artists/Index.cshtml
@model IEnumerable<MusicLibraryBrowser.ViewModels.ArtistViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>@ViewData["GenreName"] Artists</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ArtistName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr height="80">
            <td align="justify">
                <a asp-controller="Works" asp-action="Index" asp-route-artistid="@item.ArtistId">@Html.DisplayFor(modelItem => item.ArtistName)</a>
            </td>
            <td align="justify">
                @if (item.ImageId != -1)
                {
                    <a asp-controller="Images" asp-action="Index" asp-route-id="@item.ImageId">
                        <img src="@Url.Action("RenderImage", new { id = item.ImageId})" width="70" height="70" />
                    </a>
                }
                else
                {
                    <img src="~/images/person.png" width="70" height="70" />
                }
                </td>
        </tr>
}
    </tbody>
</table>