MusicLibraryBrowser/Models/Work.cs
using System;
using System.Collections.Generic;

namespace MusicLibraryBrowser
{
    public partial class Work
    {
        public Work()
        {
            WorkVersion = new HashSet<WorkVersion>();
        }

        public int WorkId { get; set; }
        public int ArtistId { get; set; }
        public string WorkName { get; set; }
        public int? ImageId { get; set; }

        public Artist Artist { get; set; }
        public ICollection<WorkVersion> WorkVersion { get; set; }
    }
}

MusicLibraryBrowser/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;

namespace MusicLibraryBrowser.Controllers
{
    public class ImagesController : Controller
    {
        private readonly musiclibraryContext _context;

        public ImagesController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Images
        public async Task<IActionResult> Index(int? id)
        {
            var images = from i in _context.Image select i;
            if (id != null)
            {
                images = images.Where(i => i.ImageId == id);
            }
            return View(await images.ToListAsync());
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            var image = await _context.Image.FindAsync(id);

            byte[] photoBack = image.Data;

            return File(photoBack, "image/png");
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Images/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ImageId,Data")] Image image)
        {
            if (ModelState.IsValid)
            {
                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(image);
        }

        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ImageId,Data")] Image image)
        {
            if (id != image.ImageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.ImageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(image);
        }

        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.ImageId == id);
        }
    }
}

MusicLibraryBrowser/Controllers/WorkVersionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;

namespace MusicLibraryBrowser.Controllers
{
    public class WorkVersionsController : Controller
    {
        private readonly musiclibraryContext _context;

        public WorkVersionsController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: WorkVersions
        public async Task<IActionResult> Index(int? workid)
        {
            var musiclibraryContext = _context.WorkVersion.Include(w => w.Work).ThenInclude(a => a.Artist).ThenInclude(g => g.Genre);
            var workversions = from v in musiclibraryContext select v;
            if (workid != null)
            {
                workversions = workversions.Where(w => w.WorkId == workid);
                if (workversions.Count() > 0)
                {
                    ViewData["ArtistName"] = workversions.First().Work.Artist.ArtistName;
                    ViewData["WorkName"] = workversions.First().Work.WorkName;
                }
//                var work = from w in _context.Work where w.WorkId == workid select w;
//                ViewData["ArtistName"] = work.FirstOrDefault().Artist.ArtistName;
//                ViewData["WorkName"] = work.FirstOrDefault().WorkName;
            }
            return View(await workversions.ToListAsync());
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            var image = await _context.Image.FindAsync(id);

            byte[] photoBack = image.Data;

            return File(photoBack, "image/png");
        }

        // GET: WorkVersions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workVersion = await _context.WorkVersion
                .Include(w => w.Work)
                .FirstOrDefaultAsync(m => m.WorkVersionId == id);
            if (workVersion == null)
            {
                return NotFound();
            }

            return View(workVersion);
        }

        // GET: WorkVersions/Create
        public IActionResult Create()
        {
            ViewData["WorkId"] = new SelectList(_context.Work, "WorkId", "WorkName");
            return View();
        }

        // POST: WorkVersions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkVersionId,WorkId,WorkVersionName,Lossless")] WorkVersion workVersion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workVersion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["WorkId"] = new SelectList(_context.Work, "WorkId", "WorkName", workVersion.WorkId);
            return View(workVersion);
        }

        // GET: WorkVersions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workVersion = await _context.WorkVersion.FindAsync(id);
            if (workVersion == null)
            {
                return NotFound();
            }
            ViewData["WorkId"] = new SelectList(_context.Work, "WorkId", "WorkName", workVersion.WorkId);
            return View(workVersion);
        }

        // POST: WorkVersions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkVersionId,WorkId,WorkVersionName,Lossless")] WorkVersion workVersion)
        {
            if (id != workVersion.WorkVersionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workVersion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkVersionExists(workVersion.WorkVersionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["WorkId"] = new SelectList(_context.Work, "WorkId", "WorkName", workVersion.WorkId);
            return View(workVersion);
        }

        // GET: WorkVersions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workVersion = await _context.WorkVersion
                .Include(w => w.Work)
                .FirstOrDefaultAsync(m => m.WorkVersionId == id);
            if (workVersion == null)
            {
                return NotFound();
            }

            return View(workVersion);
        }

        // POST: WorkVersions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workVersion = await _context.WorkVersion.FindAsync(id);
            _context.WorkVersion.Remove(workVersion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkVersionExists(int id)
        {
            return _context.WorkVersion.Any(e => e.WorkVersionId == id);
        }
    }
}

MusicLibraryBrowser/Controllers/WorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;

namespace MusicLibraryBrowser.Controllers
{
    public class WorksController : Controller
    {
        private readonly musiclibraryContext _context;

        public WorksController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Works
        public async Task<IActionResult> Index(int? id)
        {
            var musiclibraryContext = _context.Work.Include(w => w.Artist).ThenInclude(g => g.Genre);
            var works = from w in musiclibraryContext select w;
            if (id != null)
            {
                works = works.Where(w => w.ArtistId == id);
            }
            return View(await works.ToListAsync());
        }

        // GET: Works/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work
                .Include(w => w.Artist)
                .FirstOrDefaultAsync(m => m.WorkId == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        // GET: Works/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName");
            return View();
        }

        // POST: Works/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkId,ArtistId,WorkName")] Work work)
        {
            if (ModelState.IsValid)
            {
                _context.Add(work);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName", work.ArtistId);
            return View(work);
        }

        // GET: Works/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work.FindAsync(id);
            if (work == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName", work.ArtistId);
            return View(work);
        }

        // POST: Works/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkId,ArtistId,WorkName")] Work work)
        {
            if (id != work.WorkId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(work);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkExists(work.WorkId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistName", work.ArtistId);
            return View(work);
        }

        // GET: Works/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work
                .Include(w => w.Artist)
                .FirstOrDefaultAsync(m => m.WorkId == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        // POST: Works/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var work = await _context.Work.FindAsync(id);
            _context.Work.Remove(work);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkExists(int id)
        {
            return _context.Work.Any(e => e.WorkId == id);
        }
    }
}

MusicLibraryBrowser/Views/Works/Create.cshtml
@model MusicLibraryBrowser.Work

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Work</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class ="form-control" asp-items="ViewBag.ArtistId"></select>
            </div>
            <div class="form-group">
                <label asp-for="WorkName" class="control-label"></label>
                <input asp-for="WorkName" class="form-control" />
                <span asp-validation-for="WorkName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicLibraryBrowser/Views/Works/Delete.cshtml
@model MusicLibraryBrowser.Work

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Work</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorkName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artist.ArtistName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="WorkId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MusicLibraryBrowser/Views/Works/Details.cshtml
@model MusicLibraryBrowser.Work

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Work</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorkName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artist.ArtistName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.WorkId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MusicLibraryBrowser/Views/Works/Edit.cshtml
@model MusicLibraryBrowser.Work

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Work</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="WorkId" />
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkName" class="control-label"></label>
                <input asp-for="WorkName" class="form-control" />
                <span asp-validation-for="WorkName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicLibraryBrowser/Views/Works/Index.cshtml
@model IEnumerable<MusicLibraryBrowser.Work>

@{
    ViewData["Title"] = "Index";
}

<h2>@ViewData["ArtistName"] Works</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WorkName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-controller="WorkVersions" asp-action="Index" asp-route-workid="@item.WorkId">@Html.DisplayFor(modelItem => item.WorkName)</a>
            </td>
            <td>
                @if (item.ImageId != -1)
                {
//                   <img src="data:image;base64, @System.Convert.ToBase64String(item.ImageData)" width="70" height="70" />
                    <a asp-controller="Images" asp-action="Index" asp-route-id="@item.ImageId">
                        <img src="@Url.Action("RenderImage", new { id = item.ImageId})" width="70" height="70" />
                    </a>
                }
                else
                {
                    <img src="~/images/person.png" width="70" height="70" />
                }
            </td>
        </tr>
}
    </tbody>
</table>