MusicLibraryBrowser/Models/Genre.cs
using System;
using System.Collections.Generic;

namespace MusicLibraryBrowser
{
    public partial class Genre
    {
        public Genre()
        {
            Artist = new HashSet<Artist>();
        }

        public int GenreId { get; set; }
        public string GenreName { get; set; }

        public ICollection<Artist> Artist { get; set; }
    }
}

MusicLibraryBrowser/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;
using MusicLibraryBrowser.ViewModels;

namespace MusicLibraryBrowser.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly musiclibraryContext _context;

        public ArtistsController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Artists
        public async Task<IActionResult> Index(int? genreid)
        {
            var musiclibraryContext = _context.Artist.Include(a => a.Genre);

 //         var artists = from a in musiclibraryContext select a;
            var artists = (from a in _context.Artist
                          join i in _context.Image
                          on a.ImageId equals i.ImageId
                          into a1
                          from b1 in a1.DefaultIfEmpty(new Image())
                          select new ArtistViewModel
                          {
                              ArtistId = a.ArtistId,
                              GenreId = a.GenreId,
                              GenreName = a.Genre.GenreName,
                              ArtistName = a.ArtistName,
                              ImageId = a.ImageId,
                              ImageData = b1.Data
                          });

            if (genreid != null)
            {
                artists = artists.Where(a => a.GenreId == genreid);
                var genrename = from g in _context.Genre where g.GenreId == genreid select g.GenreName;
                ViewData["GenreName"] = genrename.FirstOrDefault().ToString();
            }
            return View(await artists.OrderBy(a => a.ArtistName).ToListAsync());
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            var image = await _context.Image.FindAsync(id);

            byte[] photoBack = image.Data;

            return File(photoBack, "image/png");
        }

        // GET: Artists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist
                .Include(a => a.Genre)
                .FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName");
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArtistId,GenreId,ArtistName")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName", artist.GenreId);
            return View(artist);
        }

        // GET: Artists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName", artist.GenreId);
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtistId,GenreId,ArtistName")] Artist artist)
        {
            if (id != artist.ArtistId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artist.ArtistId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genre, "GenreId", "GenreName", artist.GenreId);
            return View(artist);
        }

        // GET: Artists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist
                .Include(a => a.Genre)
                .FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artist.FindAsync(id);
            _context.Artist.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artist.Any(e => e.ArtistId == id);
        }
    }
}

MusicLibraryBrowser/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicLibraryBrowser;

namespace MusicLibraryBrowser.Controllers
{
    public class GenresController : Controller
    {
        private readonly musiclibraryContext _context;

        public GenresController(musiclibraryContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genre.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreId,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreId,GenreName")] Genre genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = await _context.Genre.FindAsync(id);
            _context.Genre.Remove(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return _context.Genre.Any(e => e.GenreId == id);
        }
    }
}

MusicLibraryBrowser/Views/Genres/Create.cshtml
@model MusicLibraryBrowser.Genre

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicLibraryBrowser/Views/Genres/Delete.cshtml
@model MusicLibraryBrowser.Genre

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GenreId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MusicLibraryBrowser/Views/Genres/Details.cshtml
@model MusicLibraryBrowser.Genre

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GenreId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MusicLibraryBrowser/Views/Genres/Edit.cshtml
@model MusicLibraryBrowser.Genre

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GenreId" />
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicLibraryBrowser/Views/Genres/Index.cshtml
@model IEnumerable<MusicLibraryBrowser.Genre>

@{
    ViewData["Title"] = "Index";
}

<h2>Genres</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GenreName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody >
@foreach (var item in Model) {
        <tr>
            <td align="justify">
                <a asp-controller="Artists" asp-action="Index"
                   asp-route-genreid="@item.GenreId">@Html.DisplayFor(modelItem => item.GenreName)</a>
            </td>
            <!--

                <td>
                    <a asp-action="Details" asp-route-id="@item.GenreId"> Details</a> |
                </td>
            -->

        </tr>
}
    </tbody>
</table>